fix: correct USER in Dockerfile to 1000 and update workflow steps for clarity [skip ci]

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -27,57 +27,49 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Test
+      - name: Prepare .npmrc
+        run: |
+          echo -e ${{ secrets.NPMRC }} | base64 -d > ~/.npmrc
+          [ -f /aws_login ] && /aws_login && cp ~/.npmrc ./ || echo "aws_login not found, skipping copy"
+
+      - name: Build documentation
+        uses: ./.github/actions/asciidoctor
+        with:
+          function: build_documentation
+        env:
+          CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
+          VARIABLE1: ${{ vars.VARIABLE1 }}
+
+      - name: Build wasm
+        uses: ./.github/actions/wasm
+        with:
+          function: build_wasm
+        env:
+          CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
+          VARIABLE1: ${{ vars.VARIABLE1 }}
+
+      - name: Build package
+        uses: ./.github/actions/node18
+        with:
+          function: build_package
+        env:
+          CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
+          # NPMRC: ${{ secrets.NPMRC }}
+
+      - name: Publish package
         continue-on-error: true
         uses: ./.github/actions/node18
         with:
-          function: test
+          function: publish_package
         env:
           CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
+          # NPMRC: ${{ secrets.NPMRC }}
 
-      # - name: Prepare .npmrc
-      #   run: |
-      #     echo -e ${{ secrets.NPMRC }} | base64 -d > ~/.npmrc
-      #     [ -f /aws_login ] && /aws_login && cp ~/.npmrc ./ || echo "aws_login not found, skipping copy"
-
-      # - name: Build documentation
-      #   uses: ./.github/actions/asciidoctor
+      # - uses: ./.github/actions/my-action
       #   with:
-      #     function: build_documentation
-      #   env:
-      #     CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
-      #     VARIABLE1: ${{ vars.VARIABLE1 }}
+      #     who-to-greet: 'Alice'
 
-      # - name: Build wasm
-      #   uses: ./.github/actions/wasm
-      #   with:
-      #     function: build_wasm
-      #   env:
-      #     CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
-      #     VARIABLE1: ${{ vars.VARIABLE1 }}
+      - name: Fix permissions
+        if: always()
+        run: echo "${PPP}" | sudo -S chown -R $(whoami):$(whoami) ../../.
 
-      # - name: Build package
-      #   uses: ./.github/actions/node18
-      #   with:
-      #     function: build_package
-      #   env:
-      #     CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
-      #     # NPMRC: ${{ secrets.NPMRC }}
-
-      # - name: Publish package
-      #   continue-on-error: true
-      #   uses: ./.github/actions/node18
-      #   with:
-      #     function: publish_package
-      #   env:
-      #     CI_COMMIT_SHORT_SHA: ${{ env.CI_COMMIT_SHORT_SHA }}
-      #     # NPMRC: ${{ secrets.NPMRC }}
-
-      # - name: Fix permissions
-      #   if: always()
-      #   run: echo "${PPP}" | sudo -S chown -R $(whoami):$(whoami) ../../.
-
-
-      # # - uses: ./.github/actions/my-action
-      # #   with:
-      # #     who-to-greet: 'Alice'
