fix: correct .npmrc preparation and ensure proper copying to action directories

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -27,10 +27,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Prepare .nmprc
+      - name: Prepare .npmrc
         run: |
           echo -e ${{ secrets.NPMRC }} | base64 -d > ~/.npmrc
-          [ -f /aws_login ] && /aws_login && cp ~/.npmrc ./.github/actions/node18/ || echo "aws_login not found, skipping copy"
+          [ -f /aws_login ] && /aws_login || echo "aws_login not found, skipping copy"
+          cat ~/.npmrc
+          cp ~/.npmrc ./
+          cp ~/.npmrc ./.github/actions/node18/
 
       - name: Build documentation
         uses: ./.github/actions/asciidoctor
