fix: update .npmrc copy path in aws_login step

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -30,7 +30,7 @@ jobs:
       - name: Prepare .npmrc
         run: |
           echo -e ${{ secrets.NPMRC }} | base64 -d > ~/.npmrc
-          [ -f /aws_login ] && /aws_login && cp ~/.npmrc ./ || echo "aws_login not found, skipping copy"
+          [ -f /aws_login ] && /aws_login && cp ~/.npmrc ./.github/actions/node18/ || echo "aws_login not found, skipping copy"
 
       - name: Build documentation
         uses: ./.github/actions/asciidoctor
